In [1]:
import numpy as np
import pandas as pd
import plotly.express as px
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler ,LabelEncoder , OneHotEncoder
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import load_model

In [2]:
data=pd.read_csv('/content/Blood Cancer Diseases dataset  - Sheet1.csv')

In [ ]:
data.head()

,Age,Gender,"Cancer_Type(AML, ALL, CLL)","Treatment_Type(Chemotherapy, Radiation)",Bone Marrow Aspiration(Positive / Negative / Not Done),Total WBC count(/cumm),Serum Protein Electrophoresis (SPEP)(Normal / Abnormal),Lymph Node Biopsy(Positive / Negative / Not Done),Lumbar Puncture (Spinal Tap),Platelet Count( (/cumm),Treatment_Outcome,"Genetic_Data(BCR-ABL, FLT3)",Side_Effects,Diagnosis_Result,Comments
0,77,Female,CLL,Targeted Therapy,Not Done,39693,Normal,Positive,Negative,324539,Ongoing,FLT3,Mild,Confirmed,Critical
1,87,Female,Lymphoma,Stem Cell Transplant,Negative,19989,Abnormal,Positive,Negative,23748,Cured,TP53,Moderate,Suspected,Critical
2,82,Male,AML,Targeted Therapy,Not Done,60567,Abnormal,Negative,Negative,166343,Cured,BCR-ABL,Moderate,Confirmed,Follow-up required
3,90,Male,ALL,Stem Cell Transplant,Positive,43125,Normal,Positive,Not Done,232304,Cured,FLT3,Mild,Confirmed,Follow-up required
4,51,Female,Multiple Myeloma,Chemotherapy,Positive,53881,Normal,Negative,Negative,329230,Cured,FLT3,NaN,Confirmed,Stable

In [4]:
data.shape

(2295, 15)

In [3]:
data.isnull().sum()

Age                                                          0
Gender                                                       0
Cancer_Type(AML, ALL, CLL)                                   0
Treatment_Type(Chemotherapy, Radiation)                      0
Bone Marrow Aspiration(Positive / Negative / Not Done)       0
Total WBC count(/cumm)                                       0
Serum Protein Electrophoresis (SPEP)(Normal / Abnormal)      0
Lymph Node Biopsy(Positive / Negative / Not Done)            0
Lumbar Puncture (Spinal Tap)                                 0
Platelet Count( (/cumm)                                      0
Treatment_Outcome                                            0
Genetic_Data(BCR-ABL, FLT3)                                536
Side_Effects                                               586
Diagnosis_Result                                             0
Comments                                                     0
dtype: int64

In [4]:
data=data.drop(columns=['Genetic_Data(BCR-ABL, FLT3)','Side_Effects'],axis=1)

In [ ]:
data.shape

(2295, 13)

In [ ]:
data.columns

Index(['Age', 'Gender', 'Cancer_Type(AML, ALL, CLL)',
       'Treatment_Type(Chemotherapy, Radiation)',
       'Bone Marrow Aspiration(Positive / Negative / Not Done)',
       'Total WBC count(/cumm)',
       'Serum Protein Electrophoresis (SPEP)(Normal / Abnormal)',
       'Lymph Node Biopsy(Positive / Negative / Not Done)',
       'Lumbar Puncture (Spinal Tap)', 'Platelet Count( (/cumm)',
       'Treatment_Outcome', 'Diagnosis_Result', 'Comments'],
      dtype='object')

In [5]:
le_Gender=LabelEncoder()
data['Gender']=le_Gender.fit_transform(data['Gender'])

In [ ]:
data.head()

,Age,Gender,"Cancer_Type(AML, ALL, CLL)","Treatment_Type(Chemotherapy, Radiation)",Bone Marrow Aspiration(Positive / Negative / Not Done),Total WBC count(/cumm),Serum Protein Electrophoresis (SPEP)(Normal / Abnormal),Lymph Node Biopsy(Positive / Negative / Not Done),Lumbar Puncture (Spinal Tap),Platelet Count( (/cumm),Treatment_Outcome,Diagnosis_Result,Comments
0,77,0,CLL,Targeted Therapy,Not Done,39693,Normal,Positive,Negative,324539,Ongoing,Confirmed,Critical
1,87,0,Lymphoma,Stem Cell Transplant,Negative,19989,Abnormal,Positive,Negative,23748,Cured,Suspected,Critical
2,82,2,AML,Targeted Therapy,Not Done,60567,Abnormal,Negative,Negative,166343,Cured,Confirmed,Follow-up required
3,90,2,ALL,Stem Cell Transplant,Positive,43125,Normal,Positive,Not Done,232304,Cured,Confirmed,Follow-up required
4,51,0,Multiple Myeloma,Chemotherapy,Positive,53881,Normal,Negative,Negative,329230,Cured,Confirmed,Stable

In [6]:
data['Treatment_Type(Chemotherapy, Radiation)'].value_counts()

Treatment_Type(Chemotherapy, Radiation)
Targeted Therapy        466
Immunotherapy           466
Chemotherapy            459
Stem Cell Transplant    457
Radiation               446
Treatment_Type            1
Name: count, dtype: int64

In [7]:
one_geo = OneHotEncoder(drop='first')

# ধরো তোমার DataFrame এ কলামের নাম 'Treatment_Type'
geo_encoded = one_geo.fit_transform(data[['Treatment_Type(Chemotherapy, Radiation)']])

# DataFrame এ রূপান্তর করো
geo_encoded_df = pd.DataFrame(
    geo_encoded.toarray(),
    columns=one_geo.get_feature_names_out(['Treatment_Type(Chemotherapy, Radiation)'])
)

print(geo_encoded_df.head())

   Treatment_Type(Chemotherapy, Radiation)_Immunotherapy  \
0                                                0.0
1                                                0.0
2                                                0.0
3                                                0.0
4                                                0.0

   Treatment_Type(Chemotherapy, Radiation)_Radiation  \
0                                                0.0
1                                                0.0
2                                                0.0
3                                                0.0
4                                                0.0

   Treatment_Type(Chemotherapy, Radiation)_Stem Cell Transplant  \
0                                                0.0
1                                                1.0
2                                                0.0
3                                                1.0
4                                                0.0

   Treatment_Type(Chemotherapy, Radiation)_Targeted Therapy  \
0                                                1.0
1                                                0.0
2                                                1.0
3                                                0.0
4                                                0.0

   Treatment_Type(Chemotherapy, Radiation)_Treatment_Type
0                                                0.0
1                                                0.0
2                                                0.0
3                                                0.0
4                                                0.0

In [8]:
data=pd.concat([data.drop(columns=['Treatment_Type(Chemotherapy, Radiation)']),geo_encoded_df],axis=1)

In [11]:
data.head()

,Age,Gender,"Cancer_Type(AML, ALL, CLL)",Bone Marrow Aspiration(Positive / Negative / Not Done),Total WBC count(/cumm),Serum Protein Electrophoresis (SPEP)(Normal / Abnormal),Lymph Node Biopsy(Positive / Negative / Not Done),Lumbar Puncture (Spinal Tap),Platelet Count( (/cumm),Treatment_Outcome,Diagnosis_Result,Comments,"Treatment_Type(Chemotherapy, Radiation)_Immunotherapy","Treatment_Type(Chemotherapy, Radiation)_Radiation","Treatment_Type(Chemotherapy, Radiation)_Stem Cell Transplant","Treatment_Type(Chemotherapy, Radiation)_Targeted Therapy","Treatment_Type(Chemotherapy, Radiation)_Treatment_Type"
0,77,0,CLL,Not Done,39693,Normal,Positive,Negative,324539,Ongoing,Confirmed,Critical,0.0,0.0,0.0,1.0,0.0
1,87,0,Lymphoma,Negative,19989,Abnormal,Positive,Negative,23748,Cured,Suspected,Critical,0.0,0.0,1.0,0.0,0.0
2,82,2,AML,Not Done,60567,Abnormal,Negative,Negative,166343,Cured,Confirmed,Follow-up required,0.0,0.0,0.0,1.0,0.0
3,90,2,ALL,Positive,43125,Normal,Positive,Not Done,232304,Cured,Confirmed,Follow-up required,0.0,0.0,1.0,0.0,0.0
4,51,0,Multiple Myeloma,Positive,53881,Normal,Negative,Negative,329230,Cured,Confirmed,Stable,0.0,0.0,0.0,0.0,0.0

In [9]:
one_geo = OneHotEncoder(drop='first')

# ধরো তোমার DataFrame এ কলামের নাম 'Treatment_Type'
geo_encoded = one_geo.fit_transform(data[['Cancer_Type(AML, ALL, CLL)']])

# DataFrame এ রূপান্তর করো
geo_encoded_df = pd.DataFrame(
    geo_encoded.toarray(),
    columns=one_geo.get_feature_names_out(['Cancer_Type(AML, ALL, CLL)'])
)

print(geo_encoded_df.head())

   Cancer_Type(AML, ALL, CLL)_AML  Cancer_Type(AML, ALL, CLL)_CLL  \
0                             0.0                             1.0
1                             0.0                             0.0
2                             1.0                             0.0
3                             0.0                             0.0
4                             0.0                             0.0

   Cancer_Type(AML, ALL, CLL)_CML  Cancer_Type(AML, ALL, CLL)_Cancer_Type  \
0                             0.0                                     0.0
1                             0.0                                     0.0
2                             0.0                                     0.0
3                             0.0                                     0.0
4                             0.0                                     0.0

   Cancer_Type(AML, ALL, CLL)_Lymphoma  \
0                                  0.0
1                                  1.0
2                                  0.0
3                                  0.0
4                                  0.0

   Cancer_Type(AML, ALL, CLL)_Multiple Myeloma
0                                          0.0
1                                          0.0
2                                          0.0
3                                          0.0
4                                          1.0

In [10]:
data=pd.concat([data.drop(columns=['Cancer_Type(AML, ALL, CLL)']),geo_encoded_df],axis=1)

In [14]:
data.head()

,Age,Gender,Bone Marrow Aspiration(Positive / Negative / Not Done),Total WBC count(/cumm),Serum Protein Electrophoresis (SPEP)(Normal / Abnormal),Lymph Node Biopsy(Positive / Negative / Not Done),Lumbar Puncture (Spinal Tap),Platelet Count( (/cumm),Treatment_Outcome,Diagnosis_Result,...,"Treatment_Type(Chemotherapy, Radiation)_Radiation","Treatment_Type(Chemotherapy, Radiation)_Stem Cell Transplant","Treatment_Type(Chemotherapy, Radiation)_Targeted Therapy","Treatment_Type(Chemotherapy, Radiation)_Treatment_Type","Cancer_Type(AML, ALL, CLL)_AML","Cancer_Type(AML, ALL, CLL)_CLL","Cancer_Type(AML, ALL, CLL)_CML","Cancer_Type(AML, ALL, CLL)_Cancer_Type","Cancer_Type(AML, ALL, CLL)_Lymphoma","Cancer_Type(AML, ALL, CLL)_Multiple Myeloma"
0,77,0,Not Done,39693,Normal,Positive,Negative,324539,Ongoing,Confirmed,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
1,87,0,Negative,19989,Abnormal,Positive,Negative,23748,Cured,Suspected,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,82,2,Not Done,60567,Abnormal,Negative,Negative,166343,Cured,Confirmed,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
3,90,2,Positive,43125,Normal,Positive,Not Done,232304,Cured,Confirmed,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,51,0,Positive,53881,Normal,Negative,Negative,329230,Cured,Confirmed,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [15]:
data['Bone Marrow Aspiration(Positive / Negative / Not Done)'].value_counts()

Bone Marrow Aspiration(Positive / Negative / Not Done)
Negative                  779
Not Done                  768
Positive                  747
Bone Marrow Aspiration      1
Name: count, dtype: int64

In [11]:
le_Bone_Marrow_Aspiration=LabelEncoder()
data['Bone Marrow Aspiration(Positive / Negative / Not Done)']=le_Bone_Marrow_Aspiration.fit_transform(data['Bone Marrow Aspiration(Positive / Negative / Not Done)'])

In [12]:
data['Serum Protein Electrophoresis (SPEP)(Normal / Abnormal)'].value_counts()

Serum Protein Electrophoresis (SPEP)(Normal / Abnormal)
Abnormal                                1151
Normal                                  1143
Serum Protein Electrophoresis (SPEP)       1
Name: count, dtype: int64

In [17]:
data.head()

,Age,Gender,Bone Marrow Aspiration(Positive / Negative / Not Done),Total WBC count(/cumm),Serum Protein Electrophoresis (SPEP)(Normal / Abnormal),Lymph Node Biopsy(Positive / Negative / Not Done),Lumbar Puncture (Spinal Tap),Platelet Count( (/cumm),Treatment_Outcome,Diagnosis_Result,...,"Treatment_Type(Chemotherapy, Radiation)_Radiation","Treatment_Type(Chemotherapy, Radiation)_Stem Cell Transplant","Treatment_Type(Chemotherapy, Radiation)_Targeted Therapy","Treatment_Type(Chemotherapy, Radiation)_Treatment_Type","Cancer_Type(AML, ALL, CLL)_AML","Cancer_Type(AML, ALL, CLL)_CLL","Cancer_Type(AML, ALL, CLL)_CML","Cancer_Type(AML, ALL, CLL)_Cancer_Type","Cancer_Type(AML, ALL, CLL)_Lymphoma","Cancer_Type(AML, ALL, CLL)_Multiple Myeloma"
0,77,0,2,39693,Normal,Positive,Negative,324539,Ongoing,Confirmed,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
1,87,0,1,19989,Abnormal,Positive,Negative,23748,Cured,Suspected,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,82,2,2,60567,Abnormal,Negative,Negative,166343,Cured,Confirmed,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
3,90,2,3,43125,Normal,Positive,Not Done,232304,Cured,Confirmed,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,51,0,3,53881,Normal,Negative,Negative,329230,Cured,Confirmed,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [13]:
le_Serum_Protein_Electrophoresis=LabelEncoder()
data['Serum Protein Electrophoresis (SPEP)(Normal / Abnormal)']=le_Serum_Protein_Electrophoresis.fit_transform(data['Serum Protein Electrophoresis (SPEP)(Normal / Abnormal)'])

In [14]:
le_Lymph_Node_Biopsy=LabelEncoder()
data['Lymph Node Biopsy(Positive / Negative / Not Done)']=le_Lymph_Node_Biopsy.fit_transform(data['Lymph Node Biopsy(Positive / Negative / Not Done)'])

In [15]:
le_Lumbar_Puncture=LabelEncoder()
data['Lumbar Puncture (Spinal Tap)']=le_Lumbar_Puncture.fit_transform(data['Lumbar Puncture (Spinal Tap)'])

In [16]:
cat_cols = data.select_dtypes(include=['object']).columns

In [17]:
cat_cols

Index(['Age', 'Total WBC count(/cumm)', 'Platelet Count( (/cumm)',
       'Treatment_Outcome', 'Diagnosis_Result', 'Comments'],
      dtype='object')

In [18]:
data_encoded = pd.get_dummies(data, drop_first=True)

In [19]:
data_encoded.head()

,Gender,Bone Marrow Aspiration(Positive / Negative / Not Done),Serum Protein Electrophoresis (SPEP)(Normal / Abnormal),Lymph Node Biopsy(Positive / Negative / Not Done),Lumbar Puncture (Spinal Tap),"Treatment_Type(Chemotherapy, Radiation)_Immunotherapy","Treatment_Type(Chemotherapy, Radiation)_Radiation","Treatment_Type(Chemotherapy, Radiation)_Stem Cell Transplant","Treatment_Type(Chemotherapy, Radiation)_Targeted Therapy","Treatment_Type(Chemotherapy, Radiation)_Treatment_Type",...,Treatment_Outcome_Ongoing,Treatment_Outcome_Treatment_Outcome,Diagnosis_Result_Diagnosis_Result,Diagnosis_Result_Ruled Out,Diagnosis_Result_Suspected,Comments_Critical,Comments_Follow-up required,Comments_No additional notes,Comments_Stable,Comments_Under Observation
0,0,2,1,3,1,0.0,0.0,0.0,1.0,0.0,...,True,False,False,False,False,True,False,False,False,False
1,0,1,0,3,1,0.0,0.0,1.0,0.0,0.0,...,False,False,False,False,True,True,False,False,False,False
2,2,2,0,1,1,0.0,0.0,0.0,1.0,0.0,...,False,False,False,False,False,False,True,False,False,False
3,2,3,1,3,2,0.0,0.0,1.0,0.0,0.0,...,False,False,False,False,False,False,True,False,False,False
4,0,3,1,1,1,0.0,0.0,0.0,0.0,0.0,...,False,False,False,False,False,False,False,False,True,False

In [20]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

cat_cols = data.select_dtypes(include=['object']).columns

transformer = ColumnTransformer(
    transformers=[('cat', OneHotEncoder(handle_unknown='ignore'), cat_cols)],
    remainder='passthrough'
)

data_encoded = transformer.fit_transform(data)

In [29]:
data_encoded

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 26725 stored elements and shape (2295, 4689)>

In [31]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2295 entries, 0 to 2294
Data columns (total 22 columns):
 #   Column                                                        Non-Null Count  Dtype
---  ------                                                        --------------  -----
 0   Age                                                           2295 non-null   object
 1   Gender                                                        2295 non-null   int64
 2   Bone Marrow Aspiration(Positive / Negative / Not Done)        2295 non-null   int64
 3   Total WBC count(/cumm)                                        2295 non-null   object
 4   Serum Protein Electrophoresis (SPEP)(Normal / Abnormal)       2295 non-null   int64
 5   Lymph Node Biopsy(Positive / Negative / Not Done)             2295 non-null   int64
 6   Lumbar Puncture (Spinal Tap)                                  2295 non-null   int64
 7   Platelet Count( (/cumm)                                       2295 non-null   object
 8   Treatment_Outcome                                             2295 non-null   object
 9   Diagnosis_Result                                              2295 non-null   object
 10  Comments                                                      2295 non-null   object
 11  Treatment_Type(Chemotherapy, Radiation)_Immunotherapy         2295 non-null   float64
 12  Treatment_Type(Chemotherapy, Radiation)_Radiation             2295 non-null   float64
 13  Treatment_Type(Chemotherapy, Radiation)_Stem Cell Transplant  2295 non-null   float64
 14  Treatment_Type(Chemotherapy, Radiation)_Targeted Therapy      2295 non-null   float64
 15  Treatment_Type(Chemotherapy, Radiation)_Treatment_Type        2295 non-null   float64
 16  Cancer_Type(AML, ALL, CLL)_AML                                2295 non-null   float64
 17  Cancer_Type(AML, ALL, CLL)_CLL                                2295 non-null   float64
 18  Cancer_Type(AML, ALL, CLL)_CML                                2295 non-null   float64
 19  Cancer_Type(AML, ALL, CLL)_Cancer_Type                        2295 non-null   float64
 20  Cancer_Type(AML, ALL, CLL)_Lymphoma                           2295 non-null   float64
 21  Cancer_Type(AML, ALL, CLL)_Multiple Myeloma                   2295 non-null   float64
dtypes: float64(11), int64(5), object(6)
memory usage: 394.6+ KB

In [21]:
one_geo = OneHotEncoder(drop='first')

# ধরো তোমার DataFrame এ কলামের নাম 'Treatment_Type'
geo_encoded = one_geo.fit_transform(data[['Total WBC count(/cumm)']])

# DataFrame এ রূপান্তর করো
geo_encoded_df = pd.DataFrame(
    geo_encoded.toarray(),
    columns=one_geo.get_feature_names_out(['Total WBC count(/cumm)'])
)

print(geo_encoded_df.head())

   Total WBC count(/cumm)_1016  Total WBC count(/cumm)_10239  \
0                          0.0                           0.0
1                          0.0                           0.0
2                          0.0                           0.0
3                          0.0                           0.0
4                          0.0                           0.0

   Total WBC count(/cumm)_1024  Total WBC count(/cumm)_10242  \
0                          0.0                           0.0
1                          0.0                           0.0
2                          0.0                           0.0
3                          0.0                           0.0
4                          0.0                           0.0

   Total WBC count(/cumm)_10296  Total WBC count(/cumm)_10325  \
0                           0.0                           0.0
1                           0.0                           0.0
2                           0.0                           0.0
3                           0.0                           0.0
4                           0.0                           0.0

   Total WBC count(/cumm)_10334  Total WBC count(/cumm)_10337  \
0                           0.0                           0.0
1                           0.0                           0.0
2                           0.0                           0.0
3                           0.0                           0.0
4                           0.0                           0.0

   Total WBC count(/cumm)_10386  Total WBC count(/cumm)_10403  ...  \
0                           0.0                           0.0  ...
1                           0.0                           0.0  ...
2                           0.0                           0.0  ...
3                           0.0                           0.0  ...
4                           0.0                           0.0  ...

   Total WBC count(/cumm)_99352  Total WBC count(/cumm)_99380  \
0                           0.0                           0.0
1                           0.0                           0.0
2                           0.0                           0.0
3                           0.0                           0.0
4                           0.0                           0.0

   Total WBC count(/cumm)_99383  Total WBC count(/cumm)_99505  \
0                           0.0                           0.0
1                           0.0                           0.0
2                           0.0                           0.0
3                           0.0                           0.0
4                           0.0                           0.0

   Total WBC count(/cumm)_99562  Total WBC count(/cumm)_99659  \
0                           0.0                           0.0
1                           0.0                           0.0
2                           0.0                           0.0
3                           0.0                           0.0
4                           0.0                           0.0

   Total WBC count(/cumm)_99753  Total WBC count(/cumm)_99793  \
0                           0.0                           0.0
1                           0.0                           0.0
2                           0.0                           0.0
3                           0.0                           0.0
4                           0.0                           0.0

   Total WBC count(/cumm)_99957  Total WBC count(/cumm)_Total WBC count(/cumm)
0                           0.0                                            0.0
1                           0.0                                            0.0
2                           0.0                                            0.0
3                           0.0                                            0.0
4                           0.0                                            0.0

[5 rows x 2276 columns]

In [23]:
data=pd.concat([data.drop(columns=['Total WBC count(/cumm)']),geo_encoded_df],axis=1)

In [22]:
one_geo = OneHotEncoder(drop='first')

# ধরো তোমার DataFrame এ কলামের নাম 'Treatment_Type'
geo_encoded = one_geo.fit_transform(data[['Age']])

# DataFrame এ রূপান্তর করো
geo_encoded_df = pd.DataFrame(
    geo_encoded.toarray(),
    columns=one_geo.get_feature_names_out(['Age'])
)

print(geo_encoded_df.head())

   Age_10  Age_11  Age_12  Age_13  Age_14  Age_15  Age_16  Age_17  Age_18  \
0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0
1     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0
2     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0
3     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0
4     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0

   Age_19  ...  Age_83  Age_84  Age_85  Age_86  Age_87  Age_88  Age_89  Age_9  \
0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0     0.0    0.0
1     0.0  ...     0.0     0.0     0.0     0.0     1.0     0.0     0.0    0.0
2     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0     0.0    0.0
3     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0     0.0    0.0
4     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0     0.0    0.0

   Age_90  Age_Age
0     0.0      0.0
1     0.0      0.0
2     0.0      0.0
3     1.0      0.0
4     0.0      0.0

[5 rows x 90 columns]

In [24]:
data=pd.concat([data.drop(columns=['Age']),geo_encoded_df],axis=1)

In [34]:
data.head()

,Gender,Bone Marrow Aspiration(Positive / Negative / Not Done),Total WBC count(/cumm),Serum Protein Electrophoresis (SPEP)(Normal / Abnormal),Lymph Node Biopsy(Positive / Negative / Not Done),Lumbar Puncture (Spinal Tap),Platelet Count( (/cumm),Treatment_Outcome,Diagnosis_Result,Comments,...,Age_83,Age_84,Age_85,Age_86,Age_87,Age_88,Age_89,Age_9,Age_90,Age_Age
0,0,2,39693,1,3,1,324539,Ongoing,Confirmed,Critical,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0,1,19989,0,3,1,23748,Cured,Suspected,Critical,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
2,2,2,60567,0,1,1,166343,Cured,Confirmed,Follow-up required,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,2,3,43125,1,3,2,232304,Cured,Confirmed,Follow-up required,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,0,3,53881,1,1,1,329230,Cured,Confirmed,Stable,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [35]:
data['Treatment_Outcome'].value_counts()

Treatment_Outcome
Cured                792
Ongoing              757
Deceased             745
Treatment_Outcome      1
Name: count, dtype: int64

In [25]:
one_geo = OneHotEncoder(drop='first')

# ধরো তোমার DataFrame এ কলামের নাম 'Treatment_Type'
geo_encoded = one_geo.fit_transform(data[['Platelet Count( (/cumm)']])

# DataFrame এ রূপান্তর করো
geo_encoded_df = pd.DataFrame(
    geo_encoded.toarray(),
    columns=one_geo.get_feature_names_out(['Platelet Count( (/cumm)'])
)

print(geo_encoded_df.head())

   Platelet Count( (/cumm)_100261  Platelet Count( (/cumm)_100333  \
0                             0.0                             0.0
1                             0.0                             0.0
2                             0.0                             0.0
3                             0.0                             0.0
4                             0.0                             0.0

   Platelet Count( (/cumm)_100568  Platelet Count( (/cumm)_100588  \
0                             0.0                             0.0
1                             0.0                             0.0
2                             0.0                             0.0
3                             0.0                             0.0
4                             0.0                             0.0

   Platelet Count( (/cumm)_100596  Platelet Count( (/cumm)_100772  \
0                             0.0                             0.0
1                             0.0                             0.0
2                             0.0                             0.0
3                             0.0                             0.0
4                             0.0                             0.0

   Platelet Count( (/cumm)_100859  Platelet Count( (/cumm)_101009  \
0                             0.0                             0.0
1                             0.0                             0.0
2                             0.0                             0.0
3                             0.0                             0.0
4                             0.0                             0.0

   Platelet Count( (/cumm)_101024  Platelet Count( (/cumm)_101087  ...  \
0                             0.0                             0.0  ...
1                             0.0                             0.0  ...
2                             0.0                             0.0  ...
3                             0.0                             0.0  ...
4                             0.0                             0.0  ...

   Platelet Count( (/cumm)_98756  Platelet Count( (/cumm)_98758  \
0                            0.0                            0.0
1                            0.0                            0.0
2                            0.0                            0.0
3                            0.0                            0.0
4                            0.0                            0.0

   Platelet Count( (/cumm)_98819  Platelet Count( (/cumm)_98954  \
0                            0.0                            0.0
1                            0.0                            0.0
2                            0.0                            0.0
3                            0.0                            0.0
4                            0.0                            0.0

   Platelet Count( (/cumm)_99221  Platelet Count( (/cumm)_99449  \
0                            0.0                            0.0
1                            0.0                            0.0
2                            0.0                            0.0
3                            0.0                            0.0
4                            0.0                            0.0

   Platelet Count( (/cumm)_99757  Platelet Count( (/cumm)_99902  \
0                            0.0                            0.0
1                            0.0                            0.0
2                            0.0                            0.0
3                            0.0                            0.0
4                            0.0                            0.0

   Platelet Count( (/cumm)_99951  Platelet Count( (/cumm)_Platelet Count
0                            0.0                                     0.0
1                            0.0                                     0.0
2                            0.0                                     0.0
3                            0.0                                     0.0
4                            0.0                                     0.0

[5 rows x 2290 columns]

In [26]:
data=pd.concat([data.drop(columns=['Platelet Count( (/cumm)']),geo_encoded_df],axis=1)

In [27]:
le_Treatment_Outcome=LabelEncoder()
data['Treatment_Outcome']=le_Treatment_Outcome.fit_transform(data['Treatment_Outcome'])

In [41]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2295 entries, 0 to 2294
Columns: 2386 entries, Gender to Total WBC count(/cumm)_Total WBC count(/cumm)
dtypes: float64(2377), int64(6), object(3)
memory usage: 41.8+ MB

In [28]:
le_Treatment_Outcome=LabelEncoder()
data['Diagnosis_Result']=le_Treatment_Outcome.fit_transform(data['Diagnosis_Result'])

In [29]:
le_Treatment_Outcome=LabelEncoder()
data['Comments']=le_Treatment_Outcome.fit_transform(data['Comments'])

In [48]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2295 entries, 0 to 2294
Columns: 4675 entries, Gender to Platelet Count( (/cumm)_Platelet Count
dtypes: float64(4667), int64(8)
memory usage: 81.9 MB

In [45]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2295 entries, 0 to 2294
Columns: 2386 entries, Gender to Total WBC count(/cumm)_Total WBC count(/cumm)
dtypes: float64(2377), int64(8), object(1)
memory usage: 41.8+ MB

In [30]:
X=data.drop(columns=['Treatment_Outcome'])
y=data['Treatment_Outcome']

In [31]:
scaler=StandardScaler()
X=scaler.fit_transform(X)

In [32]:
data.describe()

,Gender,Bone Marrow Aspiration(Positive / Negative / Not Done),Serum Protein Electrophoresis (SPEP)(Normal / Abnormal),Lymph Node Biopsy(Positive / Negative / Not Done),Lumbar Puncture (Spinal Tap),Treatment_Outcome,Diagnosis_Result,Comments,"Treatment_Type(Chemotherapy, Radiation)_Immunotherapy","Treatment_Type(Chemotherapy, Radiation)_Radiation",...,Platelet Count( (/cumm)_98756,Platelet Count( (/cumm)_98758,Platelet Count( (/cumm)_98819,Platelet Count( (/cumm)_98954,Platelet Count( (/cumm)_99221,Platelet Count( (/cumm)_99449,Platelet Count( (/cumm)_99757,Platelet Count( (/cumm)_99902,Platelet Count( (/cumm)_99951,Platelet Count( (/cumm)_Platelet Count
count,2295.000000,2295.000000,2295.000000,2295.000000,2295.000000,2295.000000,2295.000000,2295.000000,2295.000000,2295.000000,...,2295.000000,2295.000000,2295.000000,2295.000000,2295.000000,2295.000000,2295.000000,2295.000000,2295.000000,2295.000000
mean,1.044444,1.985185,0.498911,2.003050,1.995207,0.985621,1.640959,2.993464,0.203050,0.194336,...,0.000436,0.000436,0.000436,0.000436,0.000871,0.000436,0.000436,0.000436,0.000436,0.000436
std,0.999011,0.816540,0.500979,0.818002,0.815859,0.822664,1.234521,1.425711,0.402357,0.395775,...,0.020874,0.020874,0.020874,0.020874,0.029514,0.020874,0.020874,0.020874,0.020874,0.020874
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,1.000000,0.000000,1.000000,1.000000,0.000000,0.000000,2.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,2.000000,2.000000,0.000000,2.000000,2.000000,1.000000,2.000000,3.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,2.000000,3.000000,1.000000,3.000000,3.000000,2.000000,3.000000,4.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,2.000000,3.000000,2.000000,3.000000,3.000000,3.000000,3.000000,5.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [33]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=42)

In [34]:
X_train.shape

(1606, 2488)

In [35]:
X_test.shape

(689, 2488)

In [36]:
model = Sequential([
    Dense(units=32, activation='relu', input_dim=X_train.shape[1]),
    Dense(units=16, activation='relu'),
    Dense(units=8, activation='relu'),
    Dense(units=1, activation='sigmoid')
])

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [37]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [38]:
history = model.fit(X_train, y_train, epochs=10, batch_size=100, validation_data=(X_test, y_test))

Epoch 1/10
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 40ms/step - accuracy: 0.3337 - loss: 0.7739 - val_accuracy: 0.3179 - val_loss: 0.7087
Epoch 2/10
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.3686 - loss: 0.2758 - val_accuracy: 0.3251 - val_loss: 0.6265
Epoch 3/10
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.3462 - loss: -0.1585 - val_accuracy: 0.3251 - val_loss: 0.5742
Epoch 4/10
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.3462 - loss: -0.7810 - val_accuracy: 0.3295 - val_loss: 0.5343
Epoch 5/10
17/17 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - accuracy: 0.3580 - loss: -1.8612 - val_accuracy: 0.3309 - val_loss: 0.5245
Epoch 6/10
17/17 ━━━━━━━━━━━━━━━━━━━━ 1s 37ms/step - accuracy: 0.4054 - loss: -3.7956 - val_accuracy: 0.3338 - val_loss: 0.5735
Epoch 7/10
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.4265 - loss: -7.5030 - val_accuracy: 0.3454 - val_loss: 0.6892
Epoch 8/10
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.4365 - loss: -14.2119 - val_accuracy: 0.3512 - val_loss: 0.9128
Epoch 9/10
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.4614 - loss: -26.1769 - val_accuracy: 0.3512 - val_loss: 1.2909
Epoch 10/10
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.4950 - loss: -45.7829 - val_accuracy: 0.3527 - val_loss: 1.8518

In [39]:
y_pred=(model.predict(X_test)>0.5).astype(int)

22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step

In [40]:
accuracy_score(y_test,y_pred)

0.35268505079825835

In [41]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.37      0.77      0.50       250
           1       0.31      0.23      0.26       221
           2       0.00      0.00      0.00       218

    accuracy                           0.35       689
   macro avg       0.23      0.33      0.25       689
weighted avg       0.23      0.35      0.26       689

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [42]:
cm=confusion_matrix(y_test,y_pred)
cm

array([[192,  58,   0],
       [170,  51,   0],
       [162,  56,   0]])

In [47]:
import pandas as pd
import plotly.express as px
from sklearn.metrics import confusion_matrix

# ধরো y_test আর y_pred তোমার actual আর predicted labels
cm = confusion_matrix(y_test, y_pred)

# Class labels বের করো (unique values থেকে)
labels = [str(l) for l in sorted(set(y_test))]

# Confusion Matrix কে DataFrame বানাও
cm_df = pd.DataFrame(cm,
                     index=[f'Actual {l}' for l in labels],
                     columns=[f'Predicted {l}' for l in labels])

# Plotly দিয়ে visualize
fig = px.imshow(cm_df,
                text_auto=True,
                color_continuous_scale='Blues',
                title='Confusion Matrix')

fig.update_layout(
    title={'text': 'Confusion Matrix',
           'x': 0.5,
           'xanchor': 'center'},
    xaxis_title='Predicted Values',
    yaxis_title='Actual Values',
    coloraxis_showscale=True
)

fig.show()

In [48]:
model.save('saved_ann.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.